### ISSUE TITLE
${Shopify.formatMoney(price)} returns nothing

### ISSUE THREAD

**Issue by lesterdefreitas** [lucky110209/shopify-recent-viewed-products#1]
I am trying to implement this solution in the Expression theme, and for some reason ${Shopify.formatMoney(price)} outputs nothing. I there a way I can access the liquid product object here and pull {{ product.price }} rather?

**Comment by lucky110209** [comment]
I've already fixed it. You can update file jquery.products.min.js and it should works.

**Comment by lesterdefreitas** [comment]
Oh awesome, thanks man!

**Comment by lucky110209** [comment]
Fixed
